# Generated by Django 3.1.1 on 2020-09-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descripcion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='producto',
            name='igv',
            field=models.BooleanField(default=True),
        ),
    ]
