# Generated by Django 3.1.1 on 2020-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_auto_20200919_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='username',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_card',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
